[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.2"
crossbeam = "0.8"
phf = {version = "0.11", features = ["macros"]}
num-integer = "0.1.45"
